### ISSUE TITLE
Can I configure libuv to statically link to VC runtime with hunter?

### ISSUE THREAD

**Issue by hankbao** [hunter-packages/libuv#2]
* **Version**: hunter 0.23.143, libuv 1.2.4-p1
* **Platform**: Windows 7 32-bit, VS2015

Thanks for providing hunter. I'm building my app with VC runtime statically linked. However during linkage, LINK failed with exit code 120. It also threw out 

`warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs`

and

`warning LNK4217: locally defined symbol AAA imported in function BBB` 

with

`error LNK2001: unresolved external symbol CCC`

I suppose that's because libuv is built with /MD but my app was statically linked (/MT). Can I configure libuv to statically link to VC runtime with hunter and cmake?

Thank you.

**Comment by ruslo** [comment]
To customize global flags of third parties you have to use toolchain:
- https://docs.hunter.sh/en/latest/overview/customization/toolchain-id.html

Example of toolchain with MT flags:
- https://github.com/ruslo/polly/blob/master/vs-12-2013-mt.cmake
- https://github.com/ruslo/polly/blob/master/flags/vs-mt.cmake

**Comment by hankbao** [comment]
Thank you for your quickly reply. By using the toolchain from https://github.com/ruslo/polly/blob/master/flags/vs-mt.cmake I can now link my app with libuv to vc runtime statically.

Still there's one question remained I'd like to understand. Previously I tried to use

`string(REGEX REPLACE "/MD" "/MT" ${flag_var} "${${flag_var}}")`

to replace `/MD` to `/MT`. That works in my app's `CMakeLists.txt` but not in the toolchain for hunter.

I found in `vs-mt.cmake` you explicitly set the `CMAKE_C_FLAGS` & `CMAKE_CXX_FLAGS`. This works for hunter as the toolchain. Could you please elaborate the differences? Thanks.

**Comment by ruslo** [comment]
> Previously I tried to use ... to replace /MD to /MT. That works in my app's CMakeLists.txt but not in the toolchain for hunter

Because `CMAKE_CXX_FLAGS` is not filled at the moment toolchain is loading, this variable is an empty string.

Such variables will be available after `project` command, i.e., after toolchain is processed:
- https://cgold.readthedocs.io/en/latest/tutorials/project.html#tools-discovering

**Comment by hankbao** [comment]
Thank you very much.
